#ifndef CONFIG_H
#define CONFIG_H
#include <stdbool.h>
// pid default
#define PID_KP 3.0f
#define PID_KI 0.0f
#define PID_KD 0.4f
#define PID_INTEGRAL_MIN -1.0f
#define PID_INTEGRAL_MAX 1.0f
#define PID_OUTPUT_MIN -0.95f
#define PID_OUTPUT_MAX 0.95f
#define PID_HAS_PREVIOUS false
#define PID_PREVIOUS_ERROR 0.0f
#define PID_INTEGRAL 0.0f
#define TIME_STEP 1e-6f
// motor default
#define MOTOR_MIN_SPEED -20.0f
#define MOTOR_MAX_SPEED 20.0f
#define MOTOR_ACCEL_RATE 8.0f
#define MOTOR_BRAKE_RATE 12.0f
#define MOTOR_DRAG 0.8f
#define MOTOR_INITIAL_RPM 0.0f
#define MOTOR_INITIAL_LEFT_SPEED 0.0f
#define MOTOR_INITIAL_RIGHT_SPEED 0.0f

#define MOTOR_INPUT_MIN -1.0f
#define MOTOR_INPUT_MAX 1.0f
#define MOTOR_INPUT_NEUTRAL 0.0f
#define MOTOR_TWO_WHEELS 2.0f
// steering default
#define STEERING_MIN_ANGLE -0.6f
#define STEERING_MAX_ANGLE 0.6f
#define STEERING_RATE 3.0f
#define STEERING_INITIAL_ANGLE 0.0f
// track system 
#define TRACK_MAX_CONTROL_POINTS 1024
#define TRACK_MAX_CENTERLINE_POINTS 8192
#define TRACK_DEFAULT_MIN_POINT_SPACING 12.0f
#define TRACK_DEFAULT_SAMPLES_PER_SEGMENT 16
#define TRACK_DEFAULT_DRAW_THICKNESS 6.0f
#define TRACK_DEFAULT_CONTROL_COUNT 0
#define TRACK_DEFAULT_CENTERLINE_COUNT 0
#define TRACK_FINALIZED false
#define TRACK_LAST_SPLINE_POINT_OFFSET 2
#define TRACK_SPLINE_WINDOW 4 //MulRom needs 4 points
//car
#define CAR_DEFAULT_WHEELBASE 28.0f
#define CAR_DEFAULT_WHEELRADIUS 3.0f
#define CAR_MIN_WHEELBASE 0.001f
#define CAR_MIN_WHEELRADIUS 0.001f
#define CAR_DEFAULT_X 0.0f
#define CAR_DEFAULT_Y 0.0f
#define CAR_DEFAULT_HEADING 0.0f

#endif
